[package]
name = "http_client"
version = "0.2.0"
authors = ["hyunsik <hyunsik.choi@gmail.com>"]

[dependencies]
futures = "0.1.21"
http = "0.1.5"
hyper = "0.12.1"
log  = "0.4.1"
mime = "0.3.7"
serde = "1.0.32"
serde_derive = "1.0.32"
serde_json = "1.0.13"
tokio = "0.1.6"

[lib]
path = "src/lib.rs"
